baseURL = 'https://andriescourteaux.github.io/johansfietsenshop/'
languageCode = 'nl'
defaultContentLanguage = 'nl'
title = "Johan's Fietsenshop"
relativeURLs = true
disableKinds = ['taxonomy', 'term']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
