baseURL = 'https://example.org/'
languageCode = 'nl'
defaultContentLanguage = 'nl'
title = "Johan's Fietsenshop"
relativeURLs = true
disableKinds = ['taxonomy', 'term']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
